:concurrency: 5
:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    match_fetcher_job:
      cron: "*/5 * * * *"  # every 5 minutes
      class: "MatchFetcherWorker"
      queue: default

    prediction_evaluation_job:
      cron: "*/10 * * * *"  # every 10 minutes
      class: "PredictionEvaluationWorker"
      queue: default


